### PR TITLE
Tim/514 918 python data models

### PR DESCRIPTION
**Pull request by tg339**

### CODE REVIEW

File: apps/framework-cli/src/framework/python/parser.rs [hunk 1]
```diff
@@ -0,0 +1,465 @@
...
+        _ => {
+            println!("failed parsing {:?} ", body_node);
+            Err(PythonParserError::UnsupportedDataTypeError {
+                type_name: "Unsupported data type".to_string(),
+            })
+        }
+    }
+}
+
+pub fn extract_data_model_from_file(path: &PathBuf) -> Result<(), PythonParserError> {
```
Comment (callicles) [inline apps/framework-cli/src/framework/python/parser.rs]: This is the only method that needs to public in this file right?

File: apps/framework-cli/src/framework/python/parser.rs [hunk 2]
```diff
@@ -0,0 +1,465 @@
...
+            "int" => Ok(ColumnType::Int),
+            "float" => Ok(ColumnType::Float),
+            "bool" => Ok(ColumnType::Boolean),
+            "datetime" => Ok(ColumnType::DateTime),
+            _ => Err(PythonParserError::UnsupportedDataTypeError {
+                type_name: name.id.to_string(),
+            }),
+        },
+        _ => Err(PythonParserError::UnsupportedDataTypeError {
+            type_name: "Unsupported data type".to_string(),
```
Comment (callicles) [inline apps/framework-cli/src/framework/python/parser.rs]: Here you should put the name of the type that's missing. The sentence `Unsupported data Type` will be provided by the error string that you templated above.

File: apps/framework-cli/src/framework/python/parser.rs [hunk 3]
```diff
@@ -0,0 +1,465 @@
...
+};
+
+#[derive(Debug, Clone, thiserror::Error)]
+#[error("Failed to parse the python file")]
+#[non_exhaustive]
+pub enum PythonParserError {
+    FileNotFound {
+        path: PathBuf,
+    },
+    #[error("Python Parser - Unsupported data type: {type_name}")]
```
Comment (callicles) [inline apps/framework-cli/src/framework/python/parser.rs:36]: Here you will print `Python Parser - Unsupported data type: Unsupported data type` if you don't specify the data type properly at the Error building site

File: apps/framework-cli/src/framework/python/parser.rs (hunk 2 above)
Comment (callicles) [reply apps/framework-cli/src/framework/python/parser.rs]: Maybe here - the error should be a different one?

**Review by callicles — APPROVED** [review]
Small comments around error handling - otherwise looks good to me

File: apps/framework-cli/tests/python/simple.py [hunk 4]
```diff
@@ -0,0 +1,26 @@
+from dataclasses import dataclass, field
+from enum import Enum
+from typing import List, Optional
+
+
+type Key[T: (str, int)] = T
```
Comment (phiSgr) [inline apps/framework-cli/tests/python/simple.py]: I fed it to `mypy` and got `simple.py:6: error: invalid syntax  [syntax]`

Comment (phiSgr) [reply apps/framework-cli/tests/python/simple.py]: This works

```python
from typing import List, Optional, TypeVar, Union
from typing_extensions import TypeAlias

T = TypeVar('T', bound= Union[str, int])
Key: TypeAlias = T
```

Or `bound=str | int` since python 3.10

File: apps/framework-cli/tests/python/simple.py [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+    ERROR = "error"
+
+
+@dataclass 
+class MyModel:
+    name: Key[str]
+    age: int
+    flag: bool
+    status: Status
+    test_key: str = field(alias="test-key")
```
Comment (phiSgr) [inline apps/framework-cli/tests/python/simple.py]:
```
simple.py:24: error: No overload variant of "field" matches argument type "str"  [call-overload]
simple.py:24: note: Possible overload variants:
simple.py:24: note:     def [_T] field(*, default: _T, init: bool = ..., repr: bool = ..., hash: Optional[bool] = ..., compare: bool = ..., metadata: Optional[Mapping[Any, Any]] = ...) -> _T
simple.py:24: note:     def [_T] field(*, default_factory: Callable[[], _T], init: bool = ..., repr: bool = ..., hash: Optional[bool] = ..., compare: bool = ..., metadata: Optional[Mapping[Any, Any]] = ...) -> _T
simple.py:24: note:     def field(*, init: bool = ..., repr: bool = ..., hash: Optional[bool] = ..., compare: bool = ..., metadata: Optional[Mapping[Any, Any]] = ...) -> Any
```

It looks like `alias` is not a thing yet?
https://github.com/python/cpython/issues/101192

File: apps/framework-cli/tests/python/simple.py (hunk 4 above)
Comment (tg339) [reply apps/framework-cli/tests/python/simple.py]: Yeah that's the old syntax. The above works in 3.12

Comment (tg339) [reply apps/framework-cli/tests/python/simple.py]: We can add additional test cases and supported parsings. I'll keep 3.12 for now

File: apps/framework-cli/tests/python/simple.py (hunk 5 above)
Comment (tg339) [reply apps/framework-cli/tests/python/simple.py]: What python version are you using

File: apps/framework-cli/tests/python/simple.py (hunk 4 above)
Comment (phiSgr) [reply apps/framework-cli/tests/python/simple.py]: The python code runs, but mypy 1.10 on python 3.12 rejects it. Is there an alternative type checker?

File: apps/framework-cli/tests/python/simple.py (hunk 5 above)
Comment (phiSgr) [reply apps/framework-cli/tests/python/simple.py]:
```
python3.12 -m venv venv
source venv/bin/activate
pip install mypy
mypy simple.py
```

mypy version is 1.10.0

Comment (phiSgr) [reply apps/framework-cli/tests/python/simple.py]:
```
python --version
Python 3.12.3
```

```
python simple.py
Traceback (most recent call last):
  File "/Users/george/stuff/simple.py", line 18, in <module>
    class MyModel:
  File "/Users/george/stuff/simple.py", line 23, in MyModel
    test_key: str = field(alias="test-key")
                    ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: field() got an unexpected keyword argument 'alias'
```

File: apps/framework-cli/src/framework/python/parser.rs [hunk 6]
```diff
@@ -0,0 +1,29 @@
+use std::path::PathBuf;
+
+use anyhow::Error;
+use rustpython_parser::{ast, Parse};
+
+pub fn extract_data_model_from_file(path: &PathBuf) -> Result<(), Error> {
+    let schema_file = std::fs::read_to_string(path)?;
+    let ast = ast::Suite::parse(&schema_file, "<embedded>");
+
+    println!("{:#?}", ast);
```
Comment (cjus) [inline apps/framework-cli/src/framework/python/parser.rs]: Is this println for debugging purposes?

**Review by cjus — APPROVED** [review]
LGTM

**Comment by phiSgr** [comment]
Since the types are retained in Python runtime (just ignored by the interpreter), maybe we should, instead of interring the semantics from the syntax, import the user's file then do `typing.get_type_hints`.

File: apps/framework-cli/src/framework/python/scripts/framework_object_serializer.py [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+    'dataclasses': {}
+}
+
+def serialize_enum(enum):
+    return {'name': enum.name, 'value': enum.value}
+
+def serialize_type(type_):
+    type_str = str(type_)
+    class_match = re.match(r"<class '(.*)'>", type_str)
+    enum_match = re.match(r"<enum '(.*)'>", type_str)
```
Comment (phiSgr) [inline apps/framework-cli/src/framework/python/scripts/framework_object_serializer.py:40]: `.__name__`?

File: apps/framework-cli/src/framework/data_model/schema.rs [hunk 8]
```diff
@@ -130,6 +138,12 @@ impl Serialize for ColumnType {
                 state.serialize_field("elementType", inner)?;
                 state.end()
             }
+            ColumnType::Nested(nested) => {
+                let mut state = serializer.serialize_struct("Nested", 2)?;
```
Comment (phiSgr) [inline apps/framework-cli/src/framework/data_model/schema.rs:142]: need to change `fn visit_map` as well
maybe we should add a tag to the JSON object.

File: apps/framework-cli/src/framework/python/scripts/framework_object_serializer.py (hunk 7 above)
Comment (tg339) [reply apps/framework-cli/src/framework/python/scripts/framework_object_serializer.py:40]: Yeah stupid copilot stuff here. It worked so didn't bother looking into the private APIs

File: apps/framework-cli/src/framework/data_model/schema.rs (hunk 8 above)
Comment (tg339) [reply apps/framework-cli/src/framework/data_model/schema.rs:142]: What does tag mean in this case? A parent? A unique ID?

File: apps/framework-cli/src/cli.rs [hunk 9]
```diff
@@ -512,3 +512,59 @@ pub async fn cli_run() {
...
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    fn set_test_temp_dir() {
+        let test_dir = "tests/tmp";
+        std::fs::create_dir_all(test_dir).unwrap();
+        std::env::set_current_dir(test_dir).unwrap();
+    }
```
Comment (callicles) [inline apps/framework-cli/src/cli.rs:528]: We have been using `assert_fs` to create temp dirs for io in tests.

You can check it out here: 
https://github.com/514-labs/moose/blob/99f8038247cb2fd1a2ecaae4aaeb109dbc6cd9d7/apps/framework-cli/tests/cli_init.rs#L20

File: apps/framework-cli/src/cli.rs [hunk 10]
```diff
@@ -512,3 +512,59 @@ pub async fn cli_run() {
...
+        let data_model_path = project.app_dir().join("datamodels");
+
+        // Make sure all the data models are .py files
+        let data_model_files = std::fs::read_dir(data_model_path).unwrap();
+        for file in data_model_files {
+            let file = file.unwrap();
+            let file_name = file.file_name();
+            let file_name = file_name.to_str().unwrap();
+            assert!(file_name.ends_with(".py"));
+        }
```
Comment (callicles) [inline apps/framework-cli/src/cli.rs:588]: Feels like we could move the test alongside the existing `init` test or bring the other one here. 

I would lean towards bringing this with the other one as they are both integration test (IO) and the setup and tear down on the integration side is currently shorter.

File: apps/framework-cli/src/framework/python/executor.rs [hunk 11]
```diff
@@ -0,0 +1,53 @@
...
+pub enum PythonSerializers {
+    FrameworkObjectSerializer,
+    ProjectObjectSerializer,
+}
+
+impl PythonSerializers {
+    pub fn get_path(&self) -> &str {
+        match self {
+            PythonSerializers::FrameworkObjectSerializer => {
+                "src/framework/python/scripts/framework_object_serializer.py"
```
Comment (callicles) [inline apps/framework-cli/src/framework/python/executor.rs:24]: Hum this path is not going to be available at runtime in a user environment no?

What we currently do with ts is that we load the scripts at compile time in a static string and then write it on disk in the user's `.moose` directory when the CLI is run. 

We probably should do something similar here no? 

https://github.com/514-labs/moose/blob/99f8038247cb2fd1a2ecaae4aaeb109dbc6cd9d7/apps/framework-cli/src/framework/typescript/flow.rs#L10

File: apps/framework-cli/src/framework/python/parser.rs [hunk 12]
```diff
@@ -0,0 +1,741 @@
+//! # Python Parser
```
Comment (callicles) [inline apps/framework-cli/src/framework/python/parser.rs:1]: Is it that if we use the rust parser here then we don't need `executor.rs` and `framework_object_seriliazer.py` as wells as `project_serializer.py`?

File: apps/framework-cli/src/project.rs [hunk 13]
```diff
@@ -502,3 +536,55 @@ impl Project {
...
+
+    fn create_python_project() -> Project {
+        Project::new(
+            Path::new("tests/python/project"),
+            "test_project".to_string(),
+            SupportedLanguages::Python,
+        )
+    }
+
+    fn remove_python_project() {
```
Comment (callicles) [inline apps/framework-cli/src/project.rs:553]: Same as above - for those tests we should probably use `assert_fs` it will create isolated folders and gas all the setup and tear down logic in there

File: apps/framework-cli/tests/python/models/__pycache__/simple.cpython-312.pyc
Comment (callicles) [inline apps/framework-cli/tests/python/models/__pycache__/simple.cpython-312.pyc:1]: This probably should not have been committed no?

**Review by callicles — COMMENTED** [review]
I know this has been merged - but some small comments on how to improve the the code.
